---
title: "Cannabis Seed Variant Detection using Faster R-CNN"
date: 2024-03-15
author:
  - name: Toqi Tahamid Sarker
    url: https://toqitahamid.github.io/
    orcid: 0000-0003-2482-8059
    affiliation: School of Computing, Southern Illinois University
  - name: Taminul Islam
    # url: https://www2.cs.siu.edu/~kahmed/
    # orcid: 
    affiliation: School of Computing, Southern Illinois University
  - name: Khaled R. Ahmed
    url: https://www2.cs.siu.edu/~kahmed/
    # orcid: 
    affiliation: School of Computing, Southern Illinois University
categories:
  - Object Detection
  - Agriculture
  - Deep Learning
pub-info:
  reference: >-
    Toqi Tahamid Sarker, Taminul Islam and <a href="https://www2.cs.siu.edu/~kahmed/">Khaled R Ahmed</a>, “Cannabis Seed Variant Detection using Faster R-CNN,” <em>2024 IEEE International Conference on Advanced Computing and Communication Systems</em>
  
  # links:
    # - name: Preprint
    #   url: sarker-banda-solar-event-tracking-preprint.pdf
    #   icon: fa-solid fa-file-pdf
    #   local: true
    # - name: Final version
    #   url: https://doi.org/10.1109/BigData47090.2019.9006273
    #   icon: fa-solid fa-scroll
    # - name: Code
    #   url: https://github.com/toqitahamid/solar-event-tracking
    #   icon: fa-brands fa-github
    # - name: Data
    #   url: "#data-and-code"
    #   icon: fa-solid fa-table
  extra: >-
    Presented at 2024 IEEE International Conference on Advanced Computing and Communication Systems, India, March 2024.
# doi: 10.1111/1758-5899.12984
# haiku:
#   - Deep regression networks track solar phenomena to generate continuously labeled solar image data,
#   - showing great promise for the field
---


## Abstract

Analyzing and detecting cannabis seed variants is crucial for the agriculture industry. It enables precision breeding, allowing cultivators to selectively enhance desirable traits. Accurate identification of seed variants also ensures regulatory compliance, facilitating the cultivation of specific cannabis strains with defined characteristics, ultimately improving agricultural productivity and meeting diverse market demands. This paper presents a study on cannabis seed variant detection by employing a state-of-the-art object detection model Faster R-CNN. This study implemented the model on a locally sourced cannabis seed dataset in Thailand, comprising 17 distinct classes. We evaluate six Faster R-CNN models by comparing performance on various metrics and achieving a mAP score of 94.08\% and an F1 score of 95.66\%. This paper presents the first known application of deep neural network object detection models to the novel task of visually identifying cannabis seed types.


<!-- ## Code
Python implementation is available at [GitHub](https://github.com/toqitahamid/solar-event-tracking). -->


<!-- The project used several evaluation metrics to measure the accuracy of the genearated bounding boxes, and the python implementation is available at [GitHub](https://github.com/toqitahamid/solar-event-tracking). -->

<!-- ## BibTeX citation

```bibtex
@INPROCEEDINGS{9006273,
  author={Sarker, Toqi Tahamid and Banda, Juan M.},
  booktitle={2019 IEEE International Conference on Big Data (Big Data)}, 
  title={Solar Event Tracking with Deep Regression Networks: A Proof of Concept Evaluation}, 
  year={2019},
  pages={4942-4949},
  doi={10.1109/BigData47090.2019.9006273}}


``` -->
