---
title: "Solar Event Tracking with Deep Regression Networks: A Proof of Concept Evaluation"
date: 2019-12-09
author:
  - name: Toqi Tahamid Sarker
    url: https://toqitahamid.github.io/
    orcid: 0000-0003-2482-8059
    affiliation: School of Computing, Southern Illinois University
  - name: Khaled R. Ahmed
    url: https://www2.cs.siu.edu/~kahmed/
    # orcid: 
    affiliation: School of Computing, Southern Illinois University
categories:
  - Big Data
  - Solar Data Mining
  - Deep Learning
pub-info:
  reference: >-
    Toqi Tahamid Sarker, and <a href="https://www.jmbanda.com/">Juan M. Banda</a>, “Solar Event Tracking with Deep Regression Networks: A Proof of Concept Evaluation,” <em>2019 IEEE International Conference on Big Data (Big Data)</em>, 4942–49, 2019, doi: <a href="https://doi.org/10.1109/BigData47090.2019.9006273"><code>10.1109/BigData47090.2019.9006273</code></a>
  
  links:
    - name: Preprint
      url: sarker-banda-solar-event-tracking-preprint.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1109/BigData47090.2019.9006273
      icon: fa-solid fa-scroll
    - name: Code
      url: https://github.com/toqitahamid/solar-event-tracking
      icon: fa-brands fa-github
    # - name: Data
    #   url: "#data-and-code"
    #   icon: fa-solid fa-table
  extra: >-
    Presented at SABID 2019 workshop in the IEEE Big Data 2019, Los Angeles, CA, USA, December 2019.
doi: 10.1111/1758-5899.12984
# haiku:
#   - Deep regression networks track solar phenomena to generate continuously labeled solar image data,
#   - showing great promise for the field
---


## Abstract

With the advent of deep learning for computer vision tasks, the need for accurately labeled data in large volumes is vital for any application. The increasingly available large amounts of solar image data generated by the Solar Dynamic Observatory (SDO) mission make this domain particularly interesting for the development and testing of deep learning systems. The currently available labeled solar data is generated by the SDO mission's Feature Finding Team's (FFT) specialized detection modules. The major drawback of these modules is that detection and labeling is performed with a cadence of every 4 to 12 hours, depending on the module. Since SDO image data products are created every 10 seconds, there is a considerable gap between labeled observations and the continuous data stream. In order to address this shortcoming, we trained a deep regression network to track the movement of two solar phenomena: Active Region and Coronal Hole events. To the best of our knowledge, this is the first attempt of solar event tracking using a deep learning approach. Since it is impossible to fully evaluate the performance of the suggested event tracks with the original data (only partial ground truth is available), we demonstrate with several metrics the effectiveness of our approach. With the purpose of generating continuously labeled solar image data, we present this feasibility analysis showing the great promise of deep regression networks for this task.


## Code
Python implementation is available at [GitHub](https://github.com/toqitahamid/solar-event-tracking).


<!-- The project used several evaluation metrics to measure the accuracy of the genearated bounding boxes, and the python implementation is available at [GitHub](https://github.com/toqitahamid/solar-event-tracking). -->

## BibTeX citation

```bibtex
@INPROCEEDINGS{9006273,
  author={Sarker, Toqi Tahamid and Banda, Juan M.},
  booktitle={2019 IEEE International Conference on Big Data (Big Data)}, 
  title={Solar Event Tracking with Deep Regression Networks: A Proof of Concept Evaluation}, 
  year={2019},
  pages={4942-4949},
  doi={10.1109/BigData47090.2019.9006273}}


```
